apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-admin-devops
spec:
  selector:
    matchLabels:
      app: devops-admin-devops
  replicas: 1
  template:
    metadata:
      labels:
        org: tz
        team: devops
        project: admin
        environment: dev
        app: devops-admin-devops
    spec:
      imagePullSecrets:
        - name: registry-creds
      containers:
      - name: devops-admin-devops
        image: 596627550572.dkr.ecr.ap-northeast-2.amazonaws.com/tz-devops-admin:10
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 8000
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        envFrom:
        - configMapRef:
            name: devops-admin-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: devops-admin-devops
spec:
  type: NodePort
  selector:
    app: devops-admin-devops
  ports:
    - port: 80
      name: api-80
      targetPort: 8000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-admin-configmap
data:
  GIT_BRANCH: devops
  DB_HOSTNAME: host.docker.internal
  DB_R_HOSTNAME: host.docker.internal

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-admin-devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: devops-admin.devops-dev.topzone-k8s.topzone.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-admin-devops
            port:
              number: 80
  tls:
    - hosts:
        - devops-admin.devops-dev.topzone-k8s.topzone.me
      secretName: devops-admin-devops

