apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz-demo-app-vagrant
spec:
  selector:
    matchLabels:
      app: tz-demo-app-vagrant
  replicas: 1
  template:
    metadata:
      labels:
        org: tz
        team: devops
        project: admin
        environment: dev
        app: tz-demo-app-vagrant
    spec:
      hostAliases:
      - ip: "192.168.86.200"
        hostnames:
        - "harbor.harbor.topzone-k8s.topzone.com"
      imagePullSecrets:
        - name: tz-registrykey
        - name: harbor-secret
      serviceAccountName: devops-dev-svcaccount
      containers:
      - name: tz-demo-app-vagrant
        image: harbor.harbor.topzone-k8s.topzone.com/topzone-k8s/tz-demo-app:3
        imagePullPolicy: Always
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 3001
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: tz-demo-app-configmap
        - secretRef:
            name: tz-demo-app-dev-es

---
apiVersion: v1
kind: Service
metadata:
  name: tz-demo-app-vagrant
spec:
  type: NodePort
  selector:
    app: tz-demo-app-vagrant
  ports:
    - port: 80
      name: api-80
      targetPort: 3000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tz-demo-app-configmap
data:
  GIT_BRANCH: vagrant
  DB_HOSTNAME: host.docker.internal
  DB_R_HOSTNAME: host.docker.internal

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tz-demo-app-vagrant
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: vagrant-demo-app.devops-dev.topzone-k8s.topzone.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tz-demo-app-vagrant
            port:
              number: 80
  tls:
    - hosts:
        - vagrant-demo-app.devops-dev.topzone-k8s.topzone.com
      secretName: tz-demo-app-vagrant

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tz-demo-app-dev-es
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: devops-dev
    kind: SecretStore
  target:
    name: tz-demo-app-dev-es
  dataFrom:
    - extract:
        key: secret/devops-dev/tz-demo-app

